apps/rafiyol_web/lib/rafiyol_web/router.ex
defmodule RafiyolWeb.Router do
  use RafiyolWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RafiyolWeb.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RafiyolWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/words", WordController

    resources "/users", UserController, only: [:show, :new, :create, :update]


    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    scope "/learn" do
      get "/", LearnController, :show
      post "/start", LearnController, :create
      get "/session", LearnController, :edit
      post "/session", LearnController, :update
      get "/session/finish", LearnController, :delete
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", RafiyolWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RafiyolWeb.Telemetry
    end
  end
end

apps/rafiyol_web/lib/rafiyol_web/views/layout_view.ex
defmodule RafiyolWeb.LayoutView do
  use RafiyolWeb, :view
end

apps/rafiyol_web/lib/rafiyol_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Rafiyol · Phoenix Framework</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link "Rafiyol", to: Routes.page_path(@conn, :index), class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav me-auto">
            <%= if @current_user do %>
            <%= link "Words", to: Routes.word_path(@conn, :index), class: "nav-link" %>

            <%= link "Learn", to: Routes.learn_path(@conn, :show), class: "nav-link" %>

            <%= link "Account", to: Routes.user_path(@conn, :show, @current_user.id), class: "nav-link" %>
            <% end %>
          </div>
          <div class="float-right">
            <%= if @current_user do %>
            <%= button "Log out", to: Routes.session_path(@conn, :delete), method: :delete, class: "btn btn-outline-danger" %>
            <% else %>
            <%= button "Register", to: Routes.user_path(@conn, :new), method: :get, class: "btn btn-success" %>
            <%= button "Log in", to: Routes.session_path(@conn, :new), method: :get, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="my-2">
      <div class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></div>
      <div class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></div>
    </div>
    <%= @inner_content %>
  </main>
</body>

</html>

apps/rafiyol_web/lib/rafiyol_web/templates/layout/app.html.heex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>
    <%= if assigns[:page_name] do %>
      <%= @page_name <> " · Rafiyol" %>
    <% else %>
      <%= "Rafiyol" %>
    <% end %>
  </title>
  <link rel="stylesheet" href={Routes.static_path(@conn, "/css/app.css")} />
  <script defer type="text/javascript" src={Routes.static_path(@conn, "/js/app.js")}></script>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link "Rafiyol", to: Routes.page_path(@conn, :index), class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav me-auto">
            <%= if @current_user do %>
            <%= link "Words", to: Routes.word_path(@conn, :index), class: "nav-link" %>

            <%= link "Learn", to: Routes.learn_path(@conn, :show), class: "nav-link" %>

            <%= link "Account", to: Routes.user_path(@conn, :show, @current_user.id), class: "nav-link" %>
            <% end %>
          </div>
          <div class="float-right">
            <%= if @current_user do %>
            <%= button "Log out", to: Routes.session_path(@conn, :delete), method: :delete, class: "btn btn-outline-danger" %>
            <% else %>
            <%= button "Register", to: Routes.user_path(@conn, :new), method: :get, class: "btn btn-success" %>
            <%= button "Log in", to: Routes.session_path(@conn, :new), method: :get, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="my-2">
      <div class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></div>
      <div class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></div>
    </div>
    <%= @inner_content %>
  </main>
</body>

</html>